# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  sync:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Install rsync
          command: |
            sudo apt update -y
            sudo apt install -y rsync
      - run:
          name: Install GH CLI
          command: |
            sudo apt install -y git
            wget https://github.com/cli/cli/releases/download/v0.10.0/gh_0.10.0_linux_amd64.deb
            sudo dpkg -i gh_0.10.0_linux_amd64.deb
      - run:
          name: Install HUB CLI
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
            test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            brew install hub
      - run:
          name: setup python
          command: pip install git+https://github.com/pixelb/crudini.git
      - run:
          name: Apply Configuration policy
          command: |
            test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
            test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            ./sync.sh

workflows:
  sync:
    jobs:
      - approval-run:
          type: approval
      - sync:
          requires:
            - approval-run
